# Generated by Django 5.0.7 on 2024-08-01 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comentario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='publicad_comentario',
            new_name='publicado_comentario',
        ),
    ]
