# Generated by Django 5.0.7 on 2024-08-01 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_publicad_comentario_comentario_publicado_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioAdmin',
            fields=[
                ('comentario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.comentario')),
            ],
            bases=('blog.comentario',),
        ),
    ]
