# Generated by Django 5.0.7 on 2024-08-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comentarioadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComentarioAdmin',
        ),
    ]
